version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: financeiro
      POSTGRES_USER: sebas
      POSTGRES_PASSWORD: sn100102
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app:
    build: .
    container_name: app
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
